name: Run tests and publish Allure 2 and 3 reports

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

env:
  XCODE_VERSION: "16.4"
  XCRESULTS_TOOL_VERSION: "1.19.1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-reports:
    runs-on: macos-15
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Pages
        uses: actions/configure-pages@v5
    
      - name: Set Xcode ${{ env.XCODE_VERSION }}
        run: |
          sudo xcode-select --switch /Applications/Xcode_${{ env.XCODE_VERSION }}.app

      - name: Run tests against Mac OS
        run: |
          set +e
          xcodebuild test -scheme XcresultSamples -destination 'name=My Mac,arch=arm64' -testPlan UnitTests -only-test-configuration Default -resultBundlePath ./test-results/destinations/mac.xcresult
          exit 0

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

      - run: sleep 10s
  
      - run: mdls ./test-results/destinations/mac.xcresult

