name: Run tests and publish Allure 2 and 3 reports

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

env:
  XCODE_VERSION: "16.4"
  XCRESULTS_TOOL_VERSION: "1.19.1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-reports:
    runs-on: macos-15
    steps:
      - name: Run tests against Mac OS
        run: |
          set +e
          xcodebuild test -scheme XcresultSamples -destination 'name=My Mac,arch=arm64' -testPlan UnitTests -only-test-configuration Default -resultBundlePath ./output.xcresult
          exit 0
      - run: mdls ./output.xcresult
      - run: mdimport -td3 ./output.xcresult
      - run: mdimport -m -y com.apple.xcode.resultbundle -u ./output.xcresult
      - run: sleep 60s
      - run: mdls .

