name: Run tests and publish Allure 2 and 3 reports

on:
  push:
    branches:
      - 'main'
  workflow_dispatch: {}

env:
  XCODE_VERSION: "16.4"
  XCRESULTS_TOOL_VERSION: "1.19.1"

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  update-reports:
    runs-on: macos-15
    steps:
      - run: mdls .
      - run: mdimport .
      - run: mdls .
      - run: sleep 10s
      - run: mdls .

